from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


ENV_INPUT_VIDEO = "TD_CASE2_INPUT_VIDEO"
ENV_SAMPLE_EVERY_SECONDS = "TD_CASE2_SAMPLE_EVERY_SECONDS"
ENV_OUTPUT_ROOT = "TD_CASE2_OUTPUT_ROOT"
ENV_DYNAMIC_MAX_SCAN_FPS = "TD_CASE2_DYNAMIC_MAX_SCAN_FPS"
ENV_DYNAMIC_IDLE_FPS = "TD_CASE2_DYNAMIC_IDLE_FPS"
ENV_DYNAMIC_LOW_FPS = "TD_CASE2_DYNAMIC_LOW_FPS"
ENV_DYNAMIC_NORMAL_FPS = "TD_CASE2_DYNAMIC_NORMAL_FPS"
ENV_DYNAMIC_HIGH_FPS = "TD_CASE2_DYNAMIC_HIGH_FPS"
ENV_DYNAMIC_BURST_FPS = "TD_CASE2_DYNAMIC_BURST_FPS"
ENV_DYNAMIC_PREVIEW_LIMIT = "TD_CASE2_DYNAMIC_PREVIEW_LIMIT"
ENV_ROI_MODE = "TD_CASE2_ROI_MODE"
ENV_ROAD_ROI_RECT = "TD_CASE2_ROAD_ROI_RECT"
ENV_PLATE_CAPTURE_ROI_RECT = "TD_CASE2_PLATE_CAPTURE_ROI_RECT"
ENV_OBJECT_PASS_MIN_BLOB_AREA_RATIO = "TD_CASE2_OBJECT_PASS_MIN_BLOB_AREA_RATIO"
ENV_OBJECT_PASS_MIN_MOTION_PIXELS_RATIO = "TD_CASE2_OBJECT_PASS_MIN_MOTION_PIXELS_RATIO"
ENV_BURST_FPS = "TD_CASE2_BURST_FPS"
ENV_BURST_SECONDS = "TD_CASE2_BURST_SECONDS"
ENV_COOLDOWN_SECONDS = "TD_CASE2_COOLDOWN_SECONDS"
ENV_IDLE_FPS = "TD_CASE2_IDLE_FPS"
ENV_NORMAL_FPS = "TD_CASE2_NORMAL_FPS"
ENV_COOLDOWN_FPS = "TD_CASE2_COOLDOWN_FPS"
ENV_ADAPTIVE_ENABLED = "TD_CASE2_ADAPTIVE_ENABLED"
ENV_ADAPTIVE_ROI_MODE = "TD_CASE2_ADAPTIVE_ROI_MODE"
ENV_ADAPTIVE_ROAD_ROI_RECT = "TD_CASE2_ADAPTIVE_ROAD_ROI_RECT"
ENV_ADAPTIVE_MOTION_SCORE_THRESHOLD = "TD_CASE2_ADAPTIVE_MOTION_SCORE_THRESHOLD"
ENV_ADAPTIVE_MOTION_PIXELS_RATIO_THRESHOLD = "TD_CASE2_ADAPTIVE_MOTION_PIXELS_RATIO_THRESHOLD"
ENV_ADAPTIVE_HISTOGRAM_CHANGE_THRESHOLD = "TD_CASE2_ADAPTIVE_HISTOGRAM_CHANGE_THRESHOLD"
ENV_ADAPTIVE_MIN_BLOB_AREA_RATIO = "TD_CASE2_ADAPTIVE_MIN_BLOB_AREA_RATIO"
ENV_ADAPTIVE_HEARTBEAT_SECONDS = "TD_CASE2_ADAPTIVE_HEARTBEAT_SECONDS"
ENV_ADAPTIVE_MIN_SELECTED_GAP_SECONDS = "TD_CASE2_ADAPTIVE_MIN_SELECTED_GAP_SECONDS"
ENV_ADAPTIVE_PREVIEW_LIMIT = "TD_CASE2_ADAPTIVE_PREVIEW_LIMIT"
ENV_ADAPTIVE_MIN_BRIGHTNESS = "TD_CASE2_ADAPTIVE_MIN_BRIGHTNESS"
ENV_ADAPTIVE_MAX_BRIGHTNESS = "TD_CASE2_ADAPTIVE_MAX_BRIGHTNESS"
ENV_ADAPTIVE_MIN_PIXEL_VARIANCE = "TD_CASE2_ADAPTIVE_MIN_PIXEL_VARIANCE"
ENV_ADAPTIVE_MIN_BLUR_SCORE = "TD_CASE2_ADAPTIVE_MIN_BLUR_SCORE"
ENV_RUN_DIR = "TD_CASE2_RUN_DIR"
ENV_PERSON_YOLO_MODEL_PATH = "TD_CASE2_PERSON_YOLO_MODEL_PATH"
ENV_OBJECT_YOLO_MODEL_PATH = "TD_CASE2_OBJECT_YOLO_MODEL_PATH"
ENV_YOLO_MODEL_PATH = "TD_CASE2_YOLO_MODEL_PATH"
ENV_YOLO_CONF_THRESHOLD = "TD_CASE2_YOLO_CONF_THRESHOLD"
ENV_YOLO_IOU_THRESHOLD = "TD_CASE2_YOLO_IOU_THRESHOLD"
ENV_YOLO_DEVICE = "TD_CASE2_YOLO_DEVICE"
ENV_YOLO_AUDIT_FRAME_LIMIT = "TD_CASE2_YOLO_AUDIT_FRAME_LIMIT"
ENV_YOLO_SAVE_ANNOTATED = "TD_CASE2_YOLO_SAVE_ANNOTATED"
ENV_YOLO_SAVE_CROPS = "TD_CASE2_YOLO_SAVE_CROPS"
ENV_YOLO_MAX_FRAMES = "TD_CASE2_YOLO_MAX_FRAMES"
ENV_FLORENCE_MODEL_PATH = "TD_CASE2_FLORENCE_MODEL_PATH"
ENV_FLORENCE_ADAPTER_PATH = "TD_CASE2_FLORENCE_ADAPTER_PATH"
ENV_FLORENCE_DEVICE = "TD_CASE2_FLORENCE_DEVICE"
ENV_FLORENCE_AUDIT_LIMIT = "TD_CASE2_FLORENCE_AUDIT_LIMIT"
ENV_FLORENCE_TASK_MODE = "TD_CASE2_FLORENCE_TASK_MODE"
ENV_FLORENCE_MAX_NEW_TOKENS = "TD_CASE2_FLORENCE_MAX_NEW_TOKENS"
ENV_FLORENCE_SAVE_AUDIT_INPUTS = "TD_CASE2_FLORENCE_SAVE_AUDIT_INPUTS"
ENV_FLORENCE_RUN_JSON_PROMPT_TEST = "TD_CASE2_FLORENCE_RUN_JSON_PROMPT_TEST"
ENV_FLORENCE_NUM_BEAMS = "TD_CASE2_FLORENCE_NUM_BEAMS"
ENV_FLORENCE_AUDIT_NATIVE_TASKS = "TD_CASE2_FLORENCE_AUDIT_NATIVE_TASKS"
ENV_PLATE_DETECTOR_MODEL_PATH = "TD_CASE2_PLATE_DETECTOR_MODEL_PATH"
ENV_TRACKING_ENABLED = "TD_CASE2_TRACKING_ENABLED"
ENV_TRACKING_CLASSES = "TD_CASE2_TRACKING_CLASSES"
ENV_TRACKING_MIN_CONFIDENCE = "TD_CASE2_TRACKING_MIN_CONFIDENCE"
ENV_TRACKING_MIN_IOU = "TD_CASE2_TRACKING_MIN_IOU"
ENV_TRACKING_MAX_TIME_GAP_SECONDS = "TD_CASE2_TRACKING_MAX_TIME_GAP_SECONDS"
ENV_TRACKING_MAX_CENTER_DISTANCE_RATIO = "TD_CASE2_TRACKING_MAX_CENTER_DISTANCE_RATIO"
ENV_TRACKING_MAX_AREA_CHANGE_RATIO = "TD_CASE2_TRACKING_MAX_AREA_CHANGE_RATIO"
ENV_TRACKING_ALLOW_VEHICLE_CLASS_SWITCH = "TD_CASE2_TRACKING_ALLOW_VEHICLE_CLASS_SWITCH"
ENV_TRACKING_CLASS_SWITCH_MIN_IOU = "TD_CASE2_TRACKING_CLASS_SWITCH_MIN_IOU"
ENV_TRACKING_CLASS_SWITCH_MAX_CENTER_DISTANCE_RATIO = "TD_CASE2_TRACKING_CLASS_SWITCH_MAX_CENTER_DISTANCE_RATIO"
ENV_TRACKING_CLASS_SWITCH_MAX_TIME_GAP_SECONDS = "TD_CASE2_TRACKING_CLASS_SWITCH_MAX_TIME_GAP_SECONDS"
ENV_TRACKING_MIN_PERSON_CONFIDENCE = "TD_CASE2_TRACKING_MIN_PERSON_CONFIDENCE"
ENV_TRACKING_MIN_VEHICLE_CONFIDENCE = "TD_CASE2_TRACKING_MIN_VEHICLE_CONFIDENCE"
ENV_TRACKING_MIN_TRACK_LENGTH = "TD_CASE2_TRACKING_MIN_TRACK_LENGTH"
ENV_TRACKING_SAVE_PREVIEW = "TD_CASE2_TRACKING_SAVE_PREVIEW"
ENV_TRACKING_PREVIEW_LIMIT = "TD_CASE2_TRACKING_PREVIEW_LIMIT"
ENV_STEP05_TRACK_TYPES = "TD_CASE2_STEP05_TRACK_TYPES"
ENV_STEP05_INCLUDE_ALL_VEHICLE_TRACKS = "TD_CASE2_STEP05_INCLUDE_ALL_VEHICLE_TRACKS"
ENV_STEP05_PRIMARY_TOP_K_PER_TRACK = "TD_CASE2_STEP05_PRIMARY_TOP_K_PER_TRACK"
ENV_STEP05_FALLBACK_TOP_K_PER_TRACK = "TD_CASE2_STEP05_FALLBACK_TOP_K_PER_TRACK"
ENV_STEP05_MIN_PRIMARY_SCORE = "TD_CASE2_STEP05_MIN_PRIMARY_SCORE"
ENV_STEP05_MIN_FALLBACK_SCORE = "TD_CASE2_STEP05_MIN_FALLBACK_SCORE"
ENV_STEP05_REQUIRE_CROP_EXISTS = "TD_CASE2_STEP05_REQUIRE_CROP_EXISTS"
ENV_STEP05_SAVE_SELECTED_CROPS = "TD_CASE2_STEP05_SAVE_SELECTED_CROPS"
ENV_STEP05_SAVE_SELECTED_FULL_FRAMES = "TD_CASE2_STEP05_SAVE_SELECTED_FULL_FRAMES"
ENV_STEP05_SAVE_CONTACT_SHEETS = "TD_CASE2_STEP05_SAVE_CONTACT_SHEETS"
ENV_STEP05_MAX_TRACKS = "TD_CASE2_STEP05_MAX_TRACKS"
ENV_STEP05_AVOID_NEAR_DUPLICATES = "TD_CASE2_STEP05_AVOID_NEAR_DUPLICATES"
ENV_STEP05_MIN_TIME_GAP_BETWEEN_SELECTED_SECONDS = "TD_CASE2_STEP05_MIN_TIME_GAP_BETWEEN_SELECTED_SECONDS"
ENV_STEP06_PROCESS_GROUPS = "TD_CASE2_STEP06_PROCESS_GROUPS"
ENV_STEP06_PRIMARY_LIMIT = "TD_CASE2_STEP06_PRIMARY_LIMIT"
ENV_STEP06_FALLBACK_LIMIT = "TD_CASE2_STEP06_FALLBACK_LIMIT"
ENV_STEP06_DEVICE = "TD_CASE2_STEP06_DEVICE"
ENV_STEP06_MAX_NEW_TOKENS = "TD_CASE2_STEP06_MAX_NEW_TOKENS"
ENV_STEP06_NUM_BEAMS = "TD_CASE2_STEP06_NUM_BEAMS"
ENV_STEP06_SAVE_PLATE_CROPS = "TD_CASE2_STEP06_SAVE_PLATE_CROPS"
ENV_STEP06_SAVE_DEBUG_IMAGES = "TD_CASE2_STEP06_SAVE_DEBUG_IMAGES"
ENV_STEP06_MIN_PLATE_CONFIDENCE = "TD_CASE2_STEP06_MIN_PLATE_CONFIDENCE"
ENV_STEP06_RUN_CLEANING_TESTS = "TD_CASE2_STEP06_RUN_CLEANING_TESTS"
ENV_STEP06_REUSE_EXISTING_RAW_RESULTS = "TD_CASE2_STEP06_REUSE_EXISTING_RAW_RESULTS"
ENV_STEP07_INCLUDE_FALLBACK = "TD_CASE2_STEP07_INCLUDE_FALLBACK"
ENV_STEP07_INCLUDE_POSSIBLE_OCR = "TD_CASE2_STEP07_INCLUDE_POSSIBLE_OCR"
ENV_STEP07_MIN_CONFIDENCE_FOR_SEARCH = "TD_CASE2_STEP07_MIN_CONFIDENCE_FOR_SEARCH"
ENV_STEP07_REQUIRE_COLOR_FOR_COLOR_INDEX = "TD_CASE2_STEP07_REQUIRE_COLOR_FOR_COLOR_INDEX"
ENV_STEP07_REQUIRE_VERIFIED_PLATE_FOR_PLATE_INDEX = "TD_CASE2_STEP07_REQUIRE_VERIFIED_PLATE_FOR_PLATE_INDEX"
ENV_STEP07_SAVE_FLAT_INDEX = "TD_CASE2_STEP07_SAVE_FLAT_INDEX"
ENV_STEP07_SAVE_DEBUG_SUMMARY = "TD_CASE2_STEP07_SAVE_DEBUG_SUMMARY"
ENV_STEP08_ALLOW_WEAK_OCR_SEARCH = "TD_CASE2_STEP08_ALLOW_WEAK_OCR_SEARCH"
ENV_STEP08_TIME_TOLERANCE_SECONDS = "TD_CASE2_STEP08_TIME_TOLERANCE_SECONDS"
ENV_STEP08_TOP_K = "TD_CASE2_STEP08_TOP_K"
ENV_STEP08_FAIL_ON_CRITICAL_TEST_FAILURE = "TD_CASE2_STEP08_FAIL_ON_CRITICAL_TEST_FAILURE"
ENV_STEP08_SAVE_MATCH_PREVIEW = "TD_CASE2_STEP08_SAVE_MATCH_PREVIEW"
ENV_STEP09_TOP_K = "TD_CASE2_STEP09_TOP_K"
ENV_STEP09_INCLUDE_WEAK_OCR = "TD_CASE2_STEP09_INCLUDE_WEAK_OCR"
ENV_STEP09_INCLUDE_INVALID_DEBUG_FIELDS = "TD_CASE2_STEP09_INCLUDE_INVALID_DEBUG_FIELDS"
ENV_STEP09_INCLUDE_DEBUG_PATHS = "TD_CASE2_STEP09_INCLUDE_DEBUG_PATHS"
ENV_STEP09_VALIDATE_PATH_STRINGS = "TD_CASE2_STEP09_VALIDATE_PATH_STRINGS"
ENV_STEP09_BUILD_DEMO_QUERIES = "TD_CASE2_STEP09_BUILD_DEMO_QUERIES"
ENV_STEP09_RESULT_CARD_VERSION = "TD_CASE2_STEP09_RESULT_CARD_VERSION"
ENV_SEARCH_QUERY = "TD_CASE2_SEARCH_QUERY"
ENV_SEARCH_QUERIES = "TD_CASE2_SEARCH_QUERIES"
ENV_SEARCH_MODE = "TD_CASE2_SEARCH_MODE"
ENV_SEARCH_TOP_K = "TD_CASE2_SEARCH_TOP_K"
ENV_SEARCH_ALLOW_WEAK_OCR = "TD_CASE2_SEARCH_ALLOW_WEAK_OCR"
ENV_SEARCH_TIME_TOLERANCE_SECONDS = "TD_CASE2_SEARCH_TIME_TOLERANCE_SECONDS"
ENV_SEARCH_INCLUDE_FALLBACK = "TD_CASE2_SEARCH_INCLUDE_FALLBACK"
ENV_SEARCH_REQUIRE_IMAGE_PATHS = "TD_CASE2_SEARCH_REQUIRE_IMAGE_PATHS"
ENV_SEARCH_SAVE_DEBUG = "TD_CASE2_SEARCH_SAVE_DEBUG"
ENV_STEP11_WINDOW_SECONDS = "TD_CASE2_STEP11_WINDOW_SECONDS"
ENV_STEP11_WINDOW_STRIDE_SECONDS = "TD_CASE2_STEP11_WINDOW_STRIDE_SECONDS"
ENV_STEP11_MERGE_GAP_SECONDS = "TD_CASE2_STEP11_MERGE_GAP_SECONDS"
ENV_STEP11_MAX_EVENT_SECONDS = "TD_CASE2_STEP11_MAX_EVENT_SECONDS"
ENV_STEP11_CONTEXT_BEFORE_SECONDS = "TD_CASE2_STEP11_CONTEXT_BEFORE_SECONDS"
ENV_STEP11_CONTEXT_AFTER_SECONDS = "TD_CASE2_STEP11_CONTEXT_AFTER_SECONDS"
ENV_STEP11_MIN_CANDIDATE_SCORE = "TD_CASE2_STEP11_MIN_CANDIDATE_SCORE"
ENV_STEP11_TOP_K_PREVIEW = "TD_CASE2_STEP11_TOP_K_PREVIEW"
ENV_STEP11_SAVE_FLAT = "TD_CASE2_STEP11_SAVE_FLAT"
ENV_STEP11_INCLUDE_SEARCH_METADATA = "TD_CASE2_STEP11_INCLUDE_SEARCH_METADATA"
ENV_STEP12_TOP_K = "TD_CASE2_STEP12_TOP_K"
ENV_STEP12_MIN_RANKING_SCORE = "TD_CASE2_STEP12_MIN_RANKING_SCORE"
ENV_STEP12_MIN_TEMPORAL_GAP_SECONDS = "TD_CASE2_STEP12_MIN_TEMPORAL_GAP_SECONDS"
ENV_STEP12_MAX_PER_EVENT_TYPE = "TD_CASE2_STEP12_MAX_PER_EVENT_TYPE"
ENV_STEP12_MAX_PER_TIME_CLUSTER = "TD_CASE2_STEP12_MAX_PER_TIME_CLUSTER"
ENV_STEP12_PREFER_TRAFFIC_SAFETY = "TD_CASE2_STEP12_PREFER_TRAFFIC_SAFETY"
ENV_STEP12_INCLUDE_LOW_CONFIDENCE = "TD_CASE2_STEP12_INCLUDE_LOW_CONFIDENCE"
ENV_STEP12_SAVE_FLAT = "TD_CASE2_STEP12_SAVE_FLAT"
ENV_STEP12_REQUIRE_FULL_FRAME_PATH = "TD_CASE2_STEP12_REQUIRE_FULL_FRAME_PATH"
ENV_STEP13_MERGE_NEARBY_SELECTED = "TD_CASE2_STEP13_MERGE_NEARBY_SELECTED"
ENV_STEP13_MERGE_GAP_SECONDS = "TD_CASE2_STEP13_MERGE_GAP_SECONDS"
ENV_STEP13_MAX_GROUP_DURATION_SECONDS = "TD_CASE2_STEP13_MAX_GROUP_DURATION_SECONDS"
ENV_STEP13_CONTEXT_BEFORE_SECONDS = "TD_CASE2_STEP13_CONTEXT_BEFORE_SECONDS"
ENV_STEP13_CONTEXT_AFTER_SECONDS = "TD_CASE2_STEP13_CONTEXT_AFTER_SECONDS"
ENV_STEP13_STRIP_MODE = "TD_CASE2_STEP13_STRIP_MODE"
ENV_STEP13_STRIP_WIDTH = "TD_CASE2_STEP13_STRIP_WIDTH"
ENV_STEP13_STRIP_PANEL_HEIGHT = "TD_CASE2_STEP13_STRIP_PANEL_HEIGHT"
ENV_STEP13_ADD_LABELS = "TD_CASE2_STEP13_ADD_LABELS"
ENV_STEP13_SAVE_CONTACT_SHEET = "TD_CASE2_STEP13_SAVE_CONTACT_SHEET"
ENV_STEP13_REQUIRE_FULL_FRAME_EXISTS = "TD_CASE2_STEP13_REQUIRE_FULL_FRAME_EXISTS"
ENV_STEP13_MAX_INPUTS = "TD_CASE2_STEP13_MAX_INPUTS"

DEFAULT_SAMPLE_EVERY_SECONDS = 1.0
DEFAULT_DYNAMIC_MAX_SCAN_FPS = 5.0
DEFAULT_DYNAMIC_IDLE_FPS = 0.5
DEFAULT_DYNAMIC_LOW_FPS = 0.5
DEFAULT_DYNAMIC_NORMAL_FPS = 1.0
DEFAULT_DYNAMIC_HIGH_FPS = 2.0
DEFAULT_DYNAMIC_BURST_FPS = 5.0
DEFAULT_DYNAMIC_PREVIEW_LIMIT = 100
DEFAULT_ROI_MODE = "default_road"
DEFAULT_ROAD_ROI_RECT = (0.05, 0.30, 0.95, 0.95)
DEFAULT_PLATE_CAPTURE_ROI_RECT = (0.10, 0.45, 0.90, 0.95)
DEFAULT_OBJECT_PASS_MIN_BLOB_AREA_RATIO = 0.002
DEFAULT_OBJECT_PASS_MIN_MOTION_PIXELS_RATIO = 0.01
DEFAULT_BURST_FPS = 5.0
DEFAULT_BURST_SECONDS = 3.0
DEFAULT_COOLDOWN_SECONDS = 2.0
DEFAULT_IDLE_FPS = 0.5
DEFAULT_NORMAL_FPS = 1.0
DEFAULT_COOLDOWN_FPS = 1.0
DEFAULT_ADAPTIVE_ENABLED = True
DEFAULT_ADAPTIVE_ROI_MODE = "default_road"
DEFAULT_ADAPTIVE_ROAD_ROI_RECT = (0.05, 0.30, 0.95, 0.95)
DEFAULT_ADAPTIVE_MOTION_SCORE_THRESHOLD = 0.025
DEFAULT_ADAPTIVE_MOTION_PIXELS_RATIO_THRESHOLD = 0.015
DEFAULT_ADAPTIVE_HISTOGRAM_CHANGE_THRESHOLD = 0.12
DEFAULT_ADAPTIVE_MIN_BLOB_AREA_RATIO = 0.003
DEFAULT_ADAPTIVE_HEARTBEAT_SECONDS = 2.0
DEFAULT_ADAPTIVE_MIN_SELECTED_GAP_SECONDS = 0.2
DEFAULT_ADAPTIVE_PREVIEW_LIMIT = 200
DEFAULT_ADAPTIVE_MIN_BRIGHTNESS = 10.0
DEFAULT_ADAPTIVE_MAX_BRIGHTNESS = 245.0
DEFAULT_ADAPTIVE_MIN_PIXEL_VARIANCE = 15.0
DEFAULT_ADAPTIVE_MIN_BLUR_SCORE = 20.0
DEFAULT_YOLO_CONF_THRESHOLD = 0.25
DEFAULT_YOLO_IOU_THRESHOLD = 0.45
DEFAULT_YOLO_DEVICE = "auto"
DEFAULT_YOLO_AUDIT_FRAME_LIMIT = 10
DEFAULT_YOLO_SAVE_ANNOTATED = True
DEFAULT_YOLO_SAVE_CROPS = True
DEFAULT_FLORENCE_DEVICE = "auto"
DEFAULT_FLORENCE_AUDIT_LIMIT = 10
DEFAULT_FLORENCE_TASK_MODE = "ocr_and_color"
DEFAULT_FLORENCE_MAX_NEW_TOKENS = 128
DEFAULT_FLORENCE_SAVE_AUDIT_INPUTS = True
DEFAULT_FLORENCE_RUN_JSON_PROMPT_TEST = False
DEFAULT_FLORENCE_NUM_BEAMS = 3
DEFAULT_FLORENCE_AUDIT_NATIVE_TASKS = "<OCR>,<CAPTION>,<DETAILED_CAPTION>"
DEFAULT_TRACKING_ENABLED = True
DEFAULT_TRACKING_CLASSES = "person,car,motorcycle,bus,truck,bicycle,auto,van,vehicle"
DEFAULT_TRACKING_MIN_CONFIDENCE = 0.25
DEFAULT_TRACKING_MIN_IOU = 0.25
DEFAULT_TRACKING_MAX_TIME_GAP_SECONDS = 2.5
DEFAULT_TRACKING_MAX_CENTER_DISTANCE_RATIO = 0.25
DEFAULT_TRACKING_MAX_AREA_CHANGE_RATIO = 3.0
DEFAULT_TRACKING_ALLOW_VEHICLE_CLASS_SWITCH = False
DEFAULT_TRACKING_CLASS_SWITCH_MIN_IOU = 0.60
DEFAULT_TRACKING_CLASS_SWITCH_MAX_CENTER_DISTANCE_RATIO = 0.08
DEFAULT_TRACKING_CLASS_SWITCH_MAX_TIME_GAP_SECONDS = 0.6
DEFAULT_TRACKING_MIN_PERSON_CONFIDENCE = 0.35
DEFAULT_TRACKING_MIN_VEHICLE_CONFIDENCE = 0.30
DEFAULT_TRACKING_MIN_TRACK_LENGTH = 2
DEFAULT_TRACKING_SAVE_PREVIEW = True
DEFAULT_TRACKING_PREVIEW_LIMIT = 200
DEFAULT_STEP05_TRACK_TYPES = "vehicle"
DEFAULT_STEP05_INCLUDE_ALL_VEHICLE_TRACKS = True
DEFAULT_STEP05_PRIMARY_TOP_K_PER_TRACK = 3
DEFAULT_STEP05_FALLBACK_TOP_K_PER_TRACK = 1
DEFAULT_STEP05_MIN_PRIMARY_SCORE = 0.45
DEFAULT_STEP05_MIN_FALLBACK_SCORE = 0.0
DEFAULT_STEP05_REQUIRE_CROP_EXISTS = True
DEFAULT_STEP05_SAVE_SELECTED_CROPS = True
DEFAULT_STEP05_SAVE_SELECTED_FULL_FRAMES = True
DEFAULT_STEP05_SAVE_CONTACT_SHEETS = True
DEFAULT_STEP05_MAX_TRACKS = 0
DEFAULT_STEP05_AVOID_NEAR_DUPLICATES = True
DEFAULT_STEP05_MIN_TIME_GAP_BETWEEN_SELECTED_SECONDS = 0.4
DEFAULT_STEP06_PROCESS_GROUPS = "primary,fallback"
DEFAULT_STEP06_PRIMARY_LIMIT = 0
DEFAULT_STEP06_FALLBACK_LIMIT = 0
DEFAULT_STEP06_DEVICE = "auto"
DEFAULT_STEP06_MAX_NEW_TOKENS = 128
DEFAULT_STEP06_NUM_BEAMS = 3
DEFAULT_STEP06_SAVE_PLATE_CROPS = True
DEFAULT_STEP06_SAVE_DEBUG_IMAGES = True
DEFAULT_STEP06_MIN_PLATE_CONFIDENCE = 0.25
DEFAULT_STEP06_RUN_CLEANING_TESTS = True
DEFAULT_STEP06_REUSE_EXISTING_RAW_RESULTS = False
DEFAULT_STEP07_INCLUDE_FALLBACK = True
DEFAULT_STEP07_INCLUDE_POSSIBLE_OCR = True
DEFAULT_STEP07_MIN_CONFIDENCE_FOR_SEARCH = 0.0
DEFAULT_STEP07_REQUIRE_COLOR_FOR_COLOR_INDEX = False
DEFAULT_STEP07_REQUIRE_VERIFIED_PLATE_FOR_PLATE_INDEX = True
DEFAULT_STEP07_SAVE_FLAT_INDEX = True
DEFAULT_STEP07_SAVE_DEBUG_SUMMARY = True
DEFAULT_STEP08_ALLOW_WEAK_OCR_SEARCH = True
DEFAULT_STEP08_TIME_TOLERANCE_SECONDS = 3.0
DEFAULT_STEP08_TOP_K = 20
DEFAULT_STEP08_FAIL_ON_CRITICAL_TEST_FAILURE = False
DEFAULT_STEP08_SAVE_MATCH_PREVIEW = True
DEFAULT_STEP09_TOP_K = 10
DEFAULT_STEP09_INCLUDE_WEAK_OCR = True
DEFAULT_STEP09_INCLUDE_INVALID_DEBUG_FIELDS = False
DEFAULT_STEP09_INCLUDE_DEBUG_PATHS = True
DEFAULT_STEP09_VALIDATE_PATH_STRINGS = True
DEFAULT_STEP09_BUILD_DEMO_QUERIES = True
DEFAULT_STEP09_RESULT_CARD_VERSION = "v1"
DEFAULT_SEARCH_MODE = "auto"
DEFAULT_SEARCH_TOP_K = 10
DEFAULT_SEARCH_ALLOW_WEAK_OCR = True
DEFAULT_SEARCH_TIME_TOLERANCE_SECONDS = 3.0
DEFAULT_SEARCH_INCLUDE_FALLBACK = True
DEFAULT_SEARCH_REQUIRE_IMAGE_PATHS = True
DEFAULT_SEARCH_SAVE_DEBUG = True
DEFAULT_STEP11_WINDOW_SECONDS = 2.0
DEFAULT_STEP11_WINDOW_STRIDE_SECONDS = 1.0
DEFAULT_STEP11_MERGE_GAP_SECONDS = 3.0
DEFAULT_STEP11_MAX_EVENT_SECONDS = 12.0
DEFAULT_STEP11_CONTEXT_BEFORE_SECONDS = 3.0
DEFAULT_STEP11_CONTEXT_AFTER_SECONDS = 3.0
DEFAULT_STEP11_MIN_CANDIDATE_SCORE = 0.35
DEFAULT_STEP11_TOP_K_PREVIEW = 50
DEFAULT_STEP11_SAVE_FLAT = True
DEFAULT_STEP11_INCLUDE_SEARCH_METADATA = True
DEFAULT_STEP12_TOP_K = 10
DEFAULT_STEP12_MIN_RANKING_SCORE = 0.40
DEFAULT_STEP12_MIN_TEMPORAL_GAP_SECONDS = 8.0
DEFAULT_STEP12_MAX_PER_EVENT_TYPE = 4
DEFAULT_STEP12_MAX_PER_TIME_CLUSTER = 2
DEFAULT_STEP12_PREFER_TRAFFIC_SAFETY = True
DEFAULT_STEP12_INCLUDE_LOW_CONFIDENCE = True
DEFAULT_STEP12_SAVE_FLAT = True
DEFAULT_STEP12_REQUIRE_FULL_FRAME_PATH = True
DEFAULT_STEP13_MERGE_NEARBY_SELECTED = True
DEFAULT_STEP13_MERGE_GAP_SECONDS = 8.0
DEFAULT_STEP13_MAX_GROUP_DURATION_SECONDS = 14.0
DEFAULT_STEP13_CONTEXT_BEFORE_SECONDS = 3.0
DEFAULT_STEP13_CONTEXT_AFTER_SECONDS = 3.0
DEFAULT_STEP13_STRIP_MODE = "three_panel"
DEFAULT_STEP13_STRIP_WIDTH = 1440
DEFAULT_STEP13_STRIP_PANEL_HEIGHT = 540
DEFAULT_STEP13_ADD_LABELS = True
DEFAULT_STEP13_SAVE_CONTACT_SHEET = True
DEFAULT_STEP13_REQUIRE_FULL_FRAME_EXISTS = True
DEFAULT_STEP13_MAX_INPUTS = 10

# The tender demo case should accept the listed CCTV-oriented extensions and the
# common MP4 variant used in the example command.
SUPPORTED_VIDEO_EXTENSIONS = {
    ".avi",
    ".asf",
    ".mov",
    ".mkv",
    ".mpeg4",
    ".mp4",
    ".wmv",
    ".dvr",
    ".rt4",
    ".divx",
    ".264",
    ".h264",
    ".h265",
    ".ge5",
    ".ts",
    ".3gp",
}


@dataclass(frozen=True)
class TDCase2Config:
    """Runtime settings for the isolated td_case2 foundation flow."""

    input_video_path: Path
    sample_every_seconds: float
    output_root: Path


def repo_root() -> Path:
    """Return the repository root from the td_case2 test folder."""

    return Path(__file__).resolve().parents[2]


def case_root() -> Path:
    """Return the isolated td_case2 folder path."""

    return Path(__file__).resolve().parent


def default_output_root() -> Path:
    """Return the default debug-runs folder for td_case2."""

    return case_root() / "debug_runs"
