from __future__ import annotations

TRACK_MEDIA_TYPE_FULL_FRAME = "FULL_FRAME"
TRACK_MEDIA_TYPE_ANNOTATED_FULL_FRAME = "ANNOTATED_FULL_FRAME"
TRACK_MEDIA_TYPE_VEHICLE_CROP = "VEHICLE_CROP"
TRACK_MEDIA_TYPE_BEST_VEHICLE_CROP = "BEST_VEHICLE_CROP"
TRACK_MEDIA_TYPE_PLATE_CROP = "PLATE_CROP"
TRACK_MEDIA_TYPE_THUMBNAIL = "THUMBNAIL"

TRACK_MEDIA_TYPES = (
    TRACK_MEDIA_TYPE_FULL_FRAME,
    TRACK_MEDIA_TYPE_ANNOTATED_FULL_FRAME,
    TRACK_MEDIA_TYPE_VEHICLE_CROP,
    TRACK_MEDIA_TYPE_BEST_VEHICLE_CROP,
    TRACK_MEDIA_TYPE_PLATE_CROP,
    TRACK_MEDIA_TYPE_THUMBNAIL,
)

TRACK_MEDIA_TYPE_SET = set(TRACK_MEDIA_TYPES)

VEHICLE_MEDIA_TYPE_PRIORITY = {
    TRACK_MEDIA_TYPE_BEST_VEHICLE_CROP: 0,
    "BEST_OVERALL": 1,
    TRACK_MEDIA_TYPE_VEHICLE_CROP: 2,
    "TRACK_CROP": 3,
}

PLATE_MEDIA_TYPE_PRIORITY = {
    TRACK_MEDIA_TYPE_PLATE_CROP: 0,
    "NUMBER_PLATE_CROP": 1,
    "ANPR_CROP": 2,
    "OCR_CROP": 3,
}

FULL_FRAME_MEDIA_TYPE_PRIORITY = {
    TRACK_MEDIA_TYPE_FULL_FRAME: 0,
}

ANNOTATED_FULL_FRAME_MEDIA_TYPE_PRIORITY = {
    TRACK_MEDIA_TYPE_ANNOTATED_FULL_FRAME: 0,
}
