import type { HealthResponse, PaginatedResponse } from '../types/common'
import type { GlobalVehicleDetailResponse, GlobalVehicleListItem, GlobalVehicleMember } from '../types/globalVehicle'
import type { MatchListItem } from '../types/match'
import type { CameraListItem, RunDetailResponse, RunListItem } from '../types/run'
import type { MediaReference } from '../types/media'
import type { NaturalLanguageSearchResponse, VehicleSearchResponse } from '../types/search'
import type { ObservationItem, TrackDetailResponse, TrackListItem } from '../types/track'

export const healthFixture: HealthResponse = {
  status: 'ok',
  service: 'multicamera-vehicle-api',
  database: 'reachable',
  schema: 'analytics',
}

export const runsFixture: PaginatedResponse<RunListItem> = {
  items: [
    {
      id: 'run-1',
      run_code: 'RUN_20260724_151402',
      status: 'COMPLETED',
      started_at: '2026-07-24T15:14:02+05:30',
      completed_at: '2026-07-24T15:19:02+05:30',
      created_at: '2026-07-24T15:14:01+05:30',
      camera_count: 2,
      track_count: 8,
      global_vehicle_count: 7,
      processing_error_count: 0,
    },
  ],
  page: 1,
  page_size: 10,
  total: 1,
  has_next: false,
}

export const runDetailFixture: RunDetailResponse = {
  run_code: 'RUN_20260724_151402',
  status: 'COMPLETED',
  camera_summary: {
    configured_camera_count: 2,
    active_camera_count: 2,
    camera_run_count: 2,
    completed_camera_runs: 2,
  },
  track_summary: {
    track_count: 8,
    total_track_observations: 120,
  },
  enrichment_summary: {
    tracks_with_colour: 8,
    tracks_with_plate_summary: 8,
    tracks_with_media: 8,
  },
  global_object_summary: {
    global_vehicle_count: 7,
  },
  processing_error_summary: {
    processing_error_count: 0,
  },
}

export const camerasFixture: PaginatedResponse<CameraListItem> = {
  items: [
    {
      id: 'cam-1',
      camera_code: 'CAM_001',
      camera_name: 'North Gate',
      location: 'North',
      camera_run_status: 'COMPLETED',
      frames_read: 120,
      frames_processed: 120,
      detection_count: 30,
      completed_track_count: 4,
      discarded_track_count: 1,
    },
  ],
  page: 1,
  page_size: 10,
  total: 1,
  has_next: false,
}

export const mediaFixture: MediaReference[] = [
  {
    media_id: 'media-1',
    media_type: 'BEST_VEHICLE_CROP',
    availability: 'LOCAL_FILE',
    content_url: '/api/v1/media/media-1/content',
    track_uuid: 'RUN_20260724_151402:CAM_001:TRACK_4',
    frame_number: 12,
    quality_score: 0.92,
    selection_rank: 1,
    is_primary: true,
    width: 200,
    height: 100,
  },
  {
    media_id: 'media-2',
    media_type: 'PLATE_CROP',
    availability: 'LOCAL_FILE',
    content_url: '/api/v1/media/media-2/content',
    track_uuid: 'RUN_20260724_151402:CAM_001:TRACK_4',
    frame_number: 12,
    quality_score: 0.88,
    selection_rank: 1,
    is_primary: true,
    width: 120,
    height: 36,
  },
]

export const plateResultFixture = {
  raw_text: 'DL8CBF6268',
  normalized_text: 'DL8CBF6268',
  display_text: 'DL8CBF6268',
  status: 'VERIFIED',
  verification_status: 'VERIFIED',
  plate_pattern: 'STANDARD',
  ocr_confidence: 0.98,
  detector_confidence: 0.8,
  source_media_id: 'media-2',
}

export const tracksFixture: PaginatedResponse<TrackListItem> = {
  items: [
    {
      track_uuid: 'RUN_20260724_151402:CAM_001:TRACK_4',
      camera_code: 'CAM_001',
      local_track_id: 4,
      vehicle_class: 'CAR',
      class_confidence: 0.86,
      class_is_stable: true,
      class_observation_count: 5,
      lifecycle_state: 'COMPLETED',
      first_seen_at: '2026-07-24T15:14:30+05:30',
      last_seen_at: '2026-07-24T15:14:45+05:30',
      observation_count: 10,
      best_detection_confidence: 0.95,
      primary_colour: 'GREY',
      plate_result: plateResultFixture,
      canonical_plate: 'DL8CBF6268',
      plate_status: 'VERIFIED',
      plate_confidence: 0.98,
      primary_media: mediaFixture[0],
      primary_vehicle_media: mediaFixture[0],
      primary_plate_media: mediaFixture[1],
    },
  ],
  page: 1,
  page_size: 10,
  total: 1,
  has_next: false,
}

export const observationsFixture: PaginatedResponse<ObservationItem> = {
  items: [
    {
      frame_number: 12,
      timestamp: '2026-07-24T15:14:31+05:30',
      video_time_seconds: 12.4,
      bbox: { x1: 1, y1: 2, x2: 3, y2: 4 },
      detection_confidence: 0.92,
      tracker_confidence: 0.89,
      is_key_observation: true,
      class_name: 'CAR',
      raw_class_name: 'BUS',
    },
  ],
  page: 1,
  page_size: 10,
  total: 1,
  has_next: false,
}

export const trackDetailFixture: TrackDetailResponse = {
  track: tracksFixture.items[0],
  camera: {
    camera_code: 'CAM_001',
    camera_name: 'North Gate',
    location: 'North',
  },
  colour: {
    primary_colour: 'GREY',
    colour_confidence: 0.95,
  },
  plate: {
    plate_result: plateResultFixture,
    canonical_plate: 'DL8CBF6268',
    plate_status: 'VERIFIED',
    plate_confidence: 0.98,
  },
  media: mediaFixture,
  observation_summary: {
    count: 10,
    first_frame: 12,
    last_frame: 20,
    key_observation_count: 2,
  },
  class_diagnostics: {
    provisional_class_name: 'CAR',
    stable_class_name: 'CAR',
    class_is_locked: true,
    class_confidence: 0.86,
    class_winner_margin: 2.04,
    class_observation_count: 5,
    class_conflict_count: 1,
    class_scores: {
      CAR: 2.91,
      BUS: 0.87,
    },
    class_observation_counts: {
      CAR: 4,
      BUS: 1,
    },
    latest_observation_class_name: 'BUS',
  },
  global_membership: {
    linked: true,
    global_vehicle_id: 'global-1',
    global_vehicle_code: 'GVO:RUN_20260724_151402:943BD1FE7C62',
    membership_status: 'CONFIRMED',
    membership_confidence: 0.95,
    member_track_count: 2,
  },
  cross_camera_matches: [
    {
      id: 'match-1',
      decision: 'CONFIRMED',
      overall_score: 0.95,
      created_global_vehicle_id: 'global-1',
    },
  ],
  errors: [],
}

export const globalVehiclesFixture: PaginatedResponse<GlobalVehicleListItem> = {
  items: [
    {
      global_vehicle_code: 'GVO:RUN_20260724_151402:943BD1FE7C62',
      run_code: 'RUN_20260724_151402',
      status: 'CONFIRMED',
      plate_result: plateResultFixture,
      canonical_plate: 'DL8CBF6268',
      canonical_colour: 'GREY',
      canonical_vehicle_class: 'CAR',
      confidence: 0.95,
      camera_count: 2,
      track_count: 2,
      creation_method: 'CROSS_CAMERA_MATCH',
      first_seen_at: '2026-07-24T15:14:30+05:30',
      last_seen_at: '2026-07-24T15:14:50+05:30',
      primary_evidence_reference: mediaFixture[0],
      primary_vehicle_media: mediaFixture[0],
      primary_plate_media: mediaFixture[1],
    },
  ],
  page: 1,
  page_size: 10,
  total: 1,
  has_next: false,
}

export const globalVehicleMembersFixture: GlobalVehicleMember[] = [
  {
    vehicle_track_id: 'track-1',
    track_uuid: 'RUN_20260724_151402:CAM_001:TRACK_4',
    camera_code: 'CAM_001',
    vehicle_class: 'CAR',
    primary_colour: 'GREY',
    plate_result: plateResultFixture,
    canonical_plate: 'DL8CBF6268',
    plate_status: 'VERIFIED',
    plate_confidence: 0.98,
    best_detection_confidence: 0.95,
    first_seen_at: '2026-07-24T15:14:30+05:30',
    last_seen_at: '2026-07-24T15:14:45+05:30',
    association_status: 'CONFIRMED',
    association_score: 0.95,
    primary_vehicle_media: mediaFixture[0],
    primary_plate_media: mediaFixture[1],
  },
  {
    vehicle_track_id: 'track-2',
    track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
    camera_code: 'CAM_002',
    vehicle_class: 'CAR',
    primary_colour: 'GREY',
    plate_result: plateResultFixture,
    canonical_plate: 'DL8CBF6268',
    plate_status: 'VERIFIED',
    plate_confidence: 0.97,
    best_detection_confidence: 0.94,
    first_seen_at: '2026-07-24T15:14:40+05:30',
    last_seen_at: '2026-07-24T15:14:50+05:30',
    association_status: 'CONFIRMED',
    association_score: 0.95,
    primary_vehicle_media: {
      media_id: 'media-3',
      media_type: 'BEST_VEHICLE_CROP',
      availability: 'LOCAL_FILE',
      content_url: '/api/v1/media/media-3/content',
      track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
      frame_number: 14,
      quality_score: 0.9,
      selection_rank: 1,
      is_primary: true,
      width: 200,
      height: 100,
    },
    primary_plate_media: {
      media_id: 'media-4',
      media_type: 'PLATE_CROP',
      availability: 'LOCAL_FILE',
      content_url: '/api/v1/media/media-4/content',
      track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
      frame_number: 14,
      quality_score: 0.88,
      selection_rank: 1,
      is_primary: true,
      width: 120,
      height: 36,
    },
  },
]

export const globalVehicleDetailFixture: GlobalVehicleDetailResponse = {
  global_vehicle: {
    global_vehicle_code: 'GVO:RUN_20260724_151402:943BD1FE7C62',
    run_code: 'RUN_20260724_151402',
    status: 'CONFIRMED',
    plate_result: plateResultFixture,
    canonical_plate: 'DL8CBF6268',
    canonical_colour: 'GREY',
    canonical_vehicle_class: 'CAR',
    confidence: 0.95,
    camera_count: 2,
    track_count: 2,
    creation_method: 'CROSS_CAMERA_MATCH',
    first_seen_at: '2026-07-24T15:14:30+05:30',
    last_seen_at: '2026-07-24T15:14:50+05:30',
    primary_vehicle_media: mediaFixture[0],
    primary_plate_media: mediaFixture[1],
  },
  members: globalVehicleMembersFixture,
  camera_sequence: globalVehicleMembersFixture.map((member) => ({
    camera_code: member.camera_code,
    track_uuid: member.track_uuid,
  })),
  confirmed_matches: [{ id: 'match-1' }],
  possible_matches: [],
  evidence: [
    mediaFixture[0],
    mediaFixture[1],
    {
      media_id: 'media-3',
      media_type: 'BEST_VEHICLE_CROP',
      availability: 'LOCAL_FILE',
      content_url: '/api/v1/media/media-3/content',
      track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
      frame_number: 14,
      quality_score: 0.9,
      selection_rank: 1,
      is_primary: true,
      width: 200,
      height: 100,
    },
    {
      media_id: 'media-4',
      media_type: 'PLATE_CROP',
      availability: 'LOCAL_FILE',
      content_url: '/api/v1/media/media-4/content',
      track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
      frame_number: 14,
      quality_score: 0.88,
      selection_rank: 1,
      is_primary: true,
      width: 120,
      height: 36,
    },
  ],
}

export const matchesFixture: PaginatedResponse<MatchListItem> = {
  items: [
    {
      id: 'match-1',
      source_track_uuid: 'RUN_20260724_151402:CAM_001:TRACK_4',
      source_camera_code: 'CAM_001',
      candidate_track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
      candidate_camera_code: 'CAM_002',
      decision: 'CONFIRMED',
      overall_score: 0.95,
      plate_score: 1,
      class_score: 1,
      colour_score: 0.95,
      route_score: 0.8,
      time_score: 0.9,
      visual_score: 0.75,
      decision_reasons: ['plate match', 'time gap ok'],
      linked_global_vehicle_code: 'GVO:RUN_20260724_151402:943BD1FE7C62',
      rule_version: 'global_match_v1',
      source_track: {
        track_uuid: 'RUN_20260724_151402:CAM_001:TRACK_4',
        camera_code: 'CAM_001',
        vehicle_class: 'CAR',
        lifecycle_state: 'COMPLETED',
        first_seen_at: '2026-07-24T15:14:30+05:30',
        last_seen_at: '2026-07-24T15:14:45+05:30',
        best_detection_confidence: 0.95,
        primary_colour: 'GREY',
        plate_result: plateResultFixture,
        canonical_plate: 'DL8CBF6268',
        plate_status: 'VERIFIED',
        plate_confidence: 0.98,
        primary_media: mediaFixture[0],
        primary_vehicle_media: mediaFixture[0],
        primary_plate_media: mediaFixture[1],
      },
      candidate_track: {
        track_uuid: 'RUN_20260724_151402:CAM_002:TRACK_4',
        camera_code: 'CAM_002',
        vehicle_class: 'CAR',
        lifecycle_state: 'COMPLETED',
        first_seen_at: '2026-07-24T15:14:40+05:30',
        last_seen_at: '2026-07-24T15:14:50+05:30',
        best_detection_confidence: 0.94,
        primary_colour: 'GREY',
        plate_result: plateResultFixture,
        canonical_plate: 'DL8CBF6268',
        plate_status: 'VERIFIED',
        plate_confidence: 0.97,
        primary_media: globalVehicleMembersFixture[1].primary_vehicle_media,
        primary_vehicle_media: globalVehicleMembersFixture[1].primary_vehicle_media,
        primary_plate_media: globalVehicleMembersFixture[1].primary_plate_media,
      },
    },
  ],
  page: 1,
  page_size: 10,
  total: 1,
  has_next: false,
}

export const vehicleSearchFixture: VehicleSearchResponse = {
  filters: {
    run_code: 'RUN_20260725_131944',
    result_scope: 'ALL',
    vehicle_class: 'CAR',
    colour: 'GREY',
    plate: '6268',
    plate_match_type: 'ENDS_WITH',
    camera_codes: ['CAM_001', 'CAM_002'],
    multi_camera_only: true,
  },
  pagination: {
    limit: 25,
    offset: 0,
    returned: 2,
    total: 2,
    has_more: false,
  },
  results: [
    {
      result_type: 'GLOBAL_VEHICLE',
      global_vehicle_code: 'GVO:RUN_20260725_131944:FA3FCF9E3ABC',
      track_uuid: null,
      class_name: 'CAR',
      colour: 'GREY',
      plate_result: plateResultFixture,
      plate: 'DL8CBF6268',
      plate_status: 'VERIFIED',
      camera_codes: ['CAM_001', 'CAM_002'],
      first_seen_at: '2026-07-25T13:19:44+05:30',
      last_seen_at: '2026-07-25T13:20:04+05:30',
      confidence: 0.95,
      member_track_count: 2,
      primary_media: mediaFixture[0],
      primary_vehicle_media: mediaFixture[0],
      primary_plate_media: mediaFixture[1],
      match_reasons: ['exact verified plate', 'class match', 'colour match'],
      relevance_score: 127.75,
    },
    {
      result_type: 'LOCAL_TRACK',
      global_vehicle_code: null,
      track_uuid: 'RUN_20260725_131944:CAM_001:TRACK_4',
      class_name: 'CAR',
      colour: 'GREY',
      plate_result: plateResultFixture,
      plate: 'DL8CBF6268',
      plate_status: 'VERIFIED',
      camera_codes: ['CAM_001'],
      first_seen_at: '2026-07-25T13:19:44+05:30',
      last_seen_at: '2026-07-25T13:19:54+05:30',
      confidence: 0.93,
      member_track_count: 1,
      primary_media: {
        ...mediaFixture[0],
        availability: 'REFERENCE_ONLY',
        content_url: null,
        track_uuid: 'RUN_20260725_131944:CAM_001:TRACK_4',
      },
      primary_vehicle_media: {
        ...mediaFixture[0],
        availability: 'REFERENCE_ONLY',
        content_url: null,
        track_uuid: 'RUN_20260725_131944:CAM_001:TRACK_4',
      },
      primary_plate_media: {
        ...mediaFixture[1],
        availability: 'REFERENCE_ONLY',
        content_url: null,
        track_uuid: 'RUN_20260725_131944:CAM_001:TRACK_4',
      },
      match_reasons: ['partial verified plate', 'camera match'],
      relevance_score: 91.2,
    },
  ],
}

export const naturalLanguageVehicleSearchFixture: NaturalLanguageSearchResponse = {
  original_query: 'Find the grey car with plate ending in 6268.',
  parser: {
    provider: 'gemini',
    model: 'gemini-2.5-flash',
    fallback_used: false,
  },
  clarification_required: false,
  clarification_message: null,
  interpreted_filters: {
    run_code: 'RUN_20260725_131944',
    result_scope: 'GLOBAL_VEHICLES',
    vehicle_class: 'CAR',
    colour: 'GREY',
    plate: '6268',
    plate_match_type: 'ENDS_WITH',
    camera_codes: ['CAM_001', 'CAM_002'],
    multi_camera_only: true,
    limit: 25,
    offset: 0,
  },
  pagination: {
    limit: 25,
    offset: 0,
    returned: 1,
    total: 1,
    has_more: false,
  },
  results: [vehicleSearchFixture.results[0]],
}
