create table if not exists analytics.camera_relation (
    id uuid primary key default gen_random_uuid(),
    source_camera_id uuid not null,
    destination_camera_id uuid not null,
    relation_type varchar(50) not null default 'POSSIBLE_ROUTE',
    min_travel_seconds numeric,
    max_travel_seconds numeric,
    typical_travel_seconds numeric,
    distance_meters numeric,
    matching_weight numeric not null default 1,
    bidirectional boolean not null default false,
    enabled boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_camera_relation_source foreign key (source_camera_id) references analytics.camera(id),
    constraint fk_camera_relation_destination foreign key (destination_camera_id) references analytics.camera(id),
    constraint uq_camera_relation_route unique (source_camera_id, destination_camera_id, relation_type),
    constraint chk_camera_relation_distinct_cameras check (source_camera_id <> destination_camera_id),
    constraint chk_camera_relation_matching_weight check (matching_weight >= 0 and matching_weight <= 1),
    constraint chk_camera_relation_min_seconds check (min_travel_seconds is null or min_travel_seconds >= 0),
    constraint chk_camera_relation_max_seconds check (max_travel_seconds is null or max_travel_seconds >= 0),
    constraint chk_camera_relation_typical_seconds check (typical_travel_seconds is null or typical_travel_seconds >= 0),
    constraint chk_camera_relation_distance check (distance_meters is null or distance_meters >= 0),
    constraint chk_camera_relation_min_lte_max check (min_travel_seconds is null or max_travel_seconds is null or min_travel_seconds <= max_travel_seconds)
);
