create table if not exists analytics.processing_run (
    id uuid primary key default gen_random_uuid(),
    run_code varchar(100) not null,
    pipeline_name varchar(255),
    pipeline_version varchar(100),
    execution_mode varchar(30),
    status varchar(30),
    configured_camera_count integer not null default 0,
    active_camera_count integer not null default 0,
    started_at timestamptz,
    completed_at timestamptz,
    total_frames_processed bigint not null default 0,
    total_detections bigint not null default 0,
    total_track_observations bigint not null default 0,
    total_tracks bigint not null default 0,
    host_name varchar(255),
    runtime_device varchar(100),
    configuration jsonb not null default '{}'::jsonb,
    metrics jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint uq_processing_run_code unique (run_code),
    constraint chk_processing_run_execution_mode check (execution_mode is null or execution_mode in ('SEQUENTIAL', 'THREADED', 'BATCHED', 'LIVE')),
    constraint chk_processing_run_status check (status is null or status in ('QUEUED', 'RUNNING', 'COMPLETED', 'PARTIAL', 'FAILED', 'CANCELLED')),
    constraint chk_processing_run_configured_camera_count check (configured_camera_count >= 0),
    constraint chk_processing_run_active_camera_count check (active_camera_count >= 0 and active_camera_count <= configured_camera_count),
    constraint chk_processing_run_total_frames check (total_frames_processed >= 0),
    constraint chk_processing_run_total_detections check (total_detections >= 0),
    constraint chk_processing_run_total_observations check (total_track_observations >= 0),
    constraint chk_processing_run_total_tracks check (total_tracks >= 0),
    constraint chk_processing_run_time_range check (started_at is null or completed_at is null or started_at <= completed_at)
);
