create table if not exists analytics.camera_run (
    id uuid primary key default gen_random_uuid(),
    processing_run_id uuid not null,
    camera_id uuid not null,
    video_source_id uuid,
    status varchar(30),
    reader_worker_name varchar(255),
    resolved_source_fps numeric(8,3),
    effective_processing_fps numeric(8,3),
    first_frame_number bigint,
    last_frame_number bigint,
    frames_read bigint not null default 0,
    frames_processed bigint not null default 0,
    detections_count bigint not null default 0,
    track_observations_count bigint not null default 0,
    completed_tracks_count integer not null default 0,
    discarded_tracks_count integer not null default 0,
    started_at timestamptz,
    completed_at timestamptz,
    metrics jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_camera_run_processing_run foreign key (processing_run_id) references analytics.processing_run(id),
    constraint fk_camera_run_camera foreign key (camera_id) references analytics.camera(id),
    constraint fk_camera_run_video_source foreign key (video_source_id) references analytics.video_source(id),
    constraint uq_camera_run_processing_run_camera unique (processing_run_id, camera_id),
    constraint chk_camera_run_status check (status is null or status in ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED')),
    constraint chk_camera_run_resolved_fps check (resolved_source_fps is null or resolved_source_fps > 0),
    constraint chk_camera_run_effective_fps check (effective_processing_fps is null or effective_processing_fps > 0),
    constraint chk_camera_run_frames check (frames_read >= 0 and frames_processed >= 0 and detections_count >= 0 and track_observations_count >= 0),
    constraint chk_camera_run_track_counts check (completed_tracks_count >= 0 and discarded_tracks_count >= 0),
    constraint chk_camera_run_frame_range check (first_frame_number is null or last_frame_number is null or first_frame_number <= last_frame_number),
    constraint chk_camera_run_time_range check (started_at is null or completed_at is null or started_at <= completed_at)
);
