create table if not exists analytics.processing_job (
    id uuid primary key default gen_random_uuid(),
    processing_run_id uuid not null,
    camera_run_id uuid,
    job_type varchar(80) not null,
    status varchar(30) not null,
    priority integer not null default 0,
    attempt_number integer not null default 1,
    worker_name varchar(255),
    started_at timestamptz,
    completed_at timestamptz,
    processing_time_ms bigint,
    input_summary jsonb,
    output_summary jsonb,
    error_code varchar(100),
    error_message text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_processing_job_processing_run foreign key (processing_run_id) references analytics.processing_run(id),
    constraint fk_processing_job_camera_run foreign key (camera_run_id) references analytics.camera_run(id),
    constraint chk_processing_job_type check (job_type in ('READ', 'DETECT', 'TRACK', 'PERSIST', 'BEST_FRAME_SELECTION', 'PLATE_DETECTION', 'OCR', 'COLOR', 'CROSS_CAMERA_MATCH', 'EVENT_ANALYSIS')),
    constraint chk_processing_job_status check (status in ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'RETRYING', 'CANCELLED')),
    constraint chk_processing_job_attempt_number check (attempt_number > 0),
    constraint chk_processing_job_processing_time check (processing_time_ms is null or processing_time_ms >= 0),
    constraint chk_processing_job_time_range check (started_at is null or completed_at is null or started_at <= completed_at)
);
