create table if not exists analytics.vehicle_track (
    id uuid primary key default gen_random_uuid(),
    processing_run_id uuid not null,
    camera_run_id uuid not null,
    camera_id uuid not null,
    track_uuid varchar(200) not null,
    local_track_id bigint not null,
    vehicle_class varchar(40) not null,
    first_seen_at timestamptz not null,
    last_seen_at timestamptz not null,
    first_frame_number bigint not null,
    last_frame_number bigint not null,
    first_video_time_seconds numeric,
    last_video_time_seconds numeric,
    observation_count integer not null default 0,
    best_detection_confidence numeric,
    average_detection_confidence numeric,
    lifecycle_state varchar(30) not null,
    completion_reason varchar(50),
    tracker_backend varchar(100) not null,
    tracker_configuration jsonb not null default '{}'::jsonb,
    searchable boolean not null default true,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_vehicle_track_processing_run foreign key (processing_run_id) references analytics.processing_run(id),
    constraint fk_vehicle_track_camera_run foreign key (camera_run_id) references analytics.camera_run(id),
    constraint fk_vehicle_track_camera foreign key (camera_id) references analytics.camera(id),
    constraint uq_vehicle_track_track_uuid unique (track_uuid),
    constraint uq_vehicle_track_local_scope unique (processing_run_id, camera_id, local_track_id),
    constraint chk_vehicle_track_vehicle_class check (vehicle_class in ('3WHEELER', 'BUS', 'CAR', 'MOTORCYCLE', 'TRUCK', 'UNKNOWN')),
    constraint chk_vehicle_track_lifecycle_state check (lifecycle_state in ('TENTATIVE', 'ACTIVE', 'TEMPORARILY_LOST', 'COMPLETED', 'DISCARDED')),
    constraint chk_vehicle_track_observation_count check (observation_count >= 0),
    constraint chk_vehicle_track_time_range check (first_seen_at <= last_seen_at),
    constraint chk_vehicle_track_frame_range check (first_frame_number <= last_frame_number),
    constraint chk_vehicle_track_video_time_range check (first_video_time_seconds is null or last_video_time_seconds is null or first_video_time_seconds <= last_video_time_seconds),
    constraint chk_vehicle_track_best_detection_confidence check (best_detection_confidence is null or (best_detection_confidence >= 0 and best_detection_confidence <= 1)),
    constraint chk_vehicle_track_average_detection_confidence check (average_detection_confidence is null or (average_detection_confidence >= 0 and average_detection_confidence <= 1))
);
