create table if not exists analytics.track_media (
    id uuid primary key default gen_random_uuid(),
    vehicle_track_id uuid not null,
    media_type varchar(40) not null,
    storage_provider varchar(30) not null default 'LOCAL',
    storage_uri text not null,
    thumbnail_uri text,
    mime_type varchar(255),
    file_size_bytes bigint,
    checksum_sha256 varchar(64),
    frame_number bigint,
    captured_at timestamptz,
    video_time_seconds numeric,
    bbox jsonb,
    width integer,
    height integer,
    quality_score numeric,
    sharpness_score numeric,
    visibility_score numeric,
    occlusion_score numeric,
    selection_rank integer,
    is_primary boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_track_media_vehicle_track foreign key (vehicle_track_id) references analytics.vehicle_track(id),
    constraint chk_track_media_type check (media_type in ('FULL_FRAME', 'VEHICLE_CROP', 'BEST_VEHICLE_CROP', 'PLATE_CROP', 'THUMBNAIL')),
    constraint chk_track_media_storage_provider check (storage_provider in ('LOCAL', 'NAS', 'S3', 'SUPABASE_STORAGE')),
    constraint chk_track_media_file_size check (file_size_bytes is null or file_size_bytes >= 0),
    constraint chk_track_media_frame_number check (frame_number is null or frame_number >= 0),
    constraint chk_track_media_width check (width is null or width > 0),
    constraint chk_track_media_height check (height is null or height > 0),
    constraint chk_track_media_quality_score check (quality_score is null or (quality_score >= 0 and quality_score <= 1)),
    constraint chk_track_media_sharpness_score check (sharpness_score is null or (sharpness_score >= 0 and sharpness_score <= 1)),
    constraint chk_track_media_visibility_score check (visibility_score is null or (visibility_score >= 0 and visibility_score <= 1)),
    constraint chk_track_media_occlusion_score check (occlusion_score is null or (occlusion_score >= 0 and occlusion_score <= 1))
);
