create table if not exists analytics.vehicle_attribute (
    id uuid primary key default gen_random_uuid(),
    vehicle_track_id uuid not null,
    attribute_scope varchar(30) not null default 'TRACK',
    primary_color varchar(50),
    secondary_color varchar(50),
    color_confidence numeric,
    make varchar(100),
    make_confidence numeric,
    model varchar(100),
    model_confidence numeric,
    body_type varchar(100),
    body_type_confidence numeric,
    vehicle_class varchar(40),
    class_confidence numeric,
    attribute_source varchar(50),
    attribute_status varchar(30) not null default 'CURRENT',
    observation_count integer not null default 1,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_vehicle_attribute_vehicle_track foreign key (vehicle_track_id) references analytics.vehicle_track(id),
    constraint chk_vehicle_attribute_scope check (attribute_scope in ('TRACK', 'GLOBAL')),
    constraint chk_vehicle_attribute_status check (attribute_status in ('CURRENT', 'HISTORICAL', 'REJECTED')),
    constraint chk_vehicle_attribute_vehicle_class check (vehicle_class is null or vehicle_class in ('3WHEELER', 'BUS', 'CAR', 'MOTORCYCLE', 'TRUCK', 'UNKNOWN')),
    constraint chk_vehicle_attribute_color_confidence check (color_confidence is null or (color_confidence >= 0 and color_confidence <= 1)),
    constraint chk_vehicle_attribute_make_confidence check (make_confidence is null or (make_confidence >= 0 and make_confidence <= 1)),
    constraint chk_vehicle_attribute_model_confidence check (model_confidence is null or (model_confidence >= 0 and model_confidence <= 1)),
    constraint chk_vehicle_attribute_body_type_confidence check (body_type_confidence is null or (body_type_confidence >= 0 and body_type_confidence <= 1)),
    constraint chk_vehicle_attribute_class_confidence check (class_confidence is null or (class_confidence >= 0 and class_confidence <= 1)),
    constraint chk_vehicle_attribute_observation_count check (observation_count >= 0)
);
