create table if not exists analytics.plate_detection (
    id uuid primary key default gen_random_uuid(),
    vehicle_track_id uuid not null,
    track_observation_id bigint,
    track_media_id uuid,
    detected_at timestamptz not null,
    frame_number bigint,
    bbox_x1 real not null,
    bbox_y1 real not null,
    bbox_x2 real not null,
    bbox_y2 real not null,
    confidence numeric,
    detector_name varchar(100),
    detector_version varchar(100),
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_plate_detection_vehicle_track foreign key (vehicle_track_id) references analytics.vehicle_track(id),
    constraint fk_plate_detection_track_observation foreign key (track_observation_id) references analytics.track_observation(id),
    constraint fk_plate_detection_track_media foreign key (track_media_id) references analytics.track_media(id),
    constraint chk_plate_detection_frame_number check (frame_number is null or frame_number >= 0),
    constraint chk_plate_detection_bbox_x check (bbox_x2 > bbox_x1),
    constraint chk_plate_detection_bbox_y check (bbox_y2 > bbox_y1),
    constraint chk_plate_detection_confidence check (confidence is null or (confidence >= 0 and confidence <= 1))
);
