create table if not exists analytics.cross_camera_match (
    id uuid primary key default gen_random_uuid(),
    source_track_id uuid not null,
    candidate_track_id uuid not null,
    camera_relation_id uuid,
    time_gap_seconds numeric,
    plate_score numeric,
    color_score numeric,
    class_score numeric,
    temporal_score numeric,
    route_score numeric,
    appearance_score numeric,
    overall_score numeric not null,
    decision varchar(30) not null,
    decision_reason text,
    matcher_version varchar(100),
    reviewed boolean not null default false,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    track_pair_min uuid generated always as (least(source_track_id, candidate_track_id)) stored,
    track_pair_max uuid generated always as (greatest(source_track_id, candidate_track_id)) stored,
    constraint fk_cross_camera_match_source_track foreign key (source_track_id) references analytics.vehicle_track(id),
    constraint fk_cross_camera_match_candidate_track foreign key (candidate_track_id) references analytics.vehicle_track(id),
    constraint fk_cross_camera_match_camera_relation foreign key (camera_relation_id) references analytics.camera_relation(id),
    constraint uq_cross_camera_match_directed unique (source_track_id, candidate_track_id),
    constraint uq_cross_camera_match_pair unique (track_pair_min, track_pair_max),
    constraint chk_cross_camera_match_distinct_tracks check (source_track_id <> candidate_track_id),
    constraint chk_cross_camera_match_time_gap check (time_gap_seconds is null or time_gap_seconds >= 0),
    constraint chk_cross_camera_match_plate_score check (plate_score is null or (plate_score >= 0 and plate_score <= 1)),
    constraint chk_cross_camera_match_color_score check (color_score is null or (color_score >= 0 and color_score <= 1)),
    constraint chk_cross_camera_match_class_score check (class_score is null or (class_score >= 0 and class_score <= 1)),
    constraint chk_cross_camera_match_temporal_score check (temporal_score is null or (temporal_score >= 0 and temporal_score <= 1)),
    constraint chk_cross_camera_match_route_score check (route_score is null or (route_score >= 0 and route_score <= 1)),
    constraint chk_cross_camera_match_appearance_score check (appearance_score is null or (appearance_score >= 0 and appearance_score <= 1)),
    constraint chk_cross_camera_match_overall_score check (overall_score >= 0 and overall_score <= 1),
    constraint chk_cross_camera_match_decision check (decision in ('CANDIDATE', 'CONFIRMED', 'PROBABLE', 'AMBIGUOUS', 'REJECTED'))
);
