create table if not exists analytics.processing_error (
    id uuid primary key default gen_random_uuid(),
    processing_run_id uuid,
    camera_run_id uuid,
    vehicle_track_id uuid,
    processing_job_id uuid,
    stage_name varchar(100),
    worker_name varchar(255),
    severity varchar(20) not null,
    exception_type varchar(255),
    error_code varchar(100),
    message text not null,
    traceback text,
    frame_number bigint,
    structured_context jsonb not null default '{}'::jsonb,
    resolution_state varchar(30) not null default 'OPEN',
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_processing_error_processing_run foreign key (processing_run_id) references analytics.processing_run(id),
    constraint fk_processing_error_camera_run foreign key (camera_run_id) references analytics.camera_run(id),
    constraint fk_processing_error_vehicle_track foreign key (vehicle_track_id) references analytics.vehicle_track(id),
    constraint fk_processing_error_processing_job foreign key (processing_job_id) references analytics.processing_job(id),
    constraint chk_processing_error_severity check (severity in ('INFO', 'WARNING', 'ERROR', 'CRITICAL')),
    constraint chk_processing_error_frame_number check (frame_number is null or frame_number >= 0),
    constraint chk_processing_error_resolution_state check (resolution_state in ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'IGNORED'))
);
