create table if not exists analytics.event_candidate (
    id uuid primary key default gen_random_uuid(),
    processing_run_id uuid,
    camera_run_id uuid,
    camera_id uuid,
    vehicle_track_id uuid,
    global_vehicle_id uuid,
    event_type varchar(80) not null,
    event_status varchar(30) not null default 'CANDIDATE',
    event_time timestamptz not null,
    event_end_time timestamptz,
    confidence numeric,
    event_payload jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_event_candidate_processing_run foreign key (processing_run_id) references analytics.processing_run(id),
    constraint fk_event_candidate_camera_run foreign key (camera_run_id) references analytics.camera_run(id),
    constraint fk_event_candidate_camera foreign key (camera_id) references analytics.camera(id),
    constraint fk_event_candidate_vehicle_track foreign key (vehicle_track_id) references analytics.vehicle_track(id),
    constraint fk_event_candidate_global_vehicle foreign key (global_vehicle_id) references analytics.global_vehicle(id),
    constraint chk_event_candidate_status check (event_status in ('CANDIDATE', 'PROBABLE', 'CONFIRMED', 'REJECTED')),
    constraint chk_event_candidate_confidence check (confidence is null or (confidence >= 0 and confidence <= 1)),
    constraint chk_event_candidate_time_range check (event_end_time is null or event_time <= event_end_time)
);
