create table if not exists analytics.analytics_event (
    id uuid primary key default gen_random_uuid(),
    event_candidate_id uuid,
    processing_run_id uuid,
    camera_id uuid,
    vehicle_track_id uuid,
    global_vehicle_id uuid,
    event_code varchar(120) not null,
    event_type varchar(80) not null,
    event_status varchar(30) not null default 'CONFIRMED',
    event_time timestamptz not null,
    event_end_time timestamptz,
    confidence numeric,
    title varchar(255),
    description text,
    event_payload jsonb not null default '{}'::jsonb,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint fk_analytics_event_candidate foreign key (event_candidate_id) references analytics.event_candidate(id),
    constraint fk_analytics_event_processing_run foreign key (processing_run_id) references analytics.processing_run(id),
    constraint fk_analytics_event_camera foreign key (camera_id) references analytics.camera(id),
    constraint fk_analytics_event_vehicle_track foreign key (vehicle_track_id) references analytics.vehicle_track(id),
    constraint fk_analytics_event_global_vehicle foreign key (global_vehicle_id) references analytics.global_vehicle(id),
    constraint uq_analytics_event_code unique (event_code),
    constraint chk_analytics_event_status check (event_status in ('CONFIRMED', 'ACTIVE', 'CLOSED', 'CANCELLED')),
    constraint chk_analytics_event_confidence check (confidence is null or (confidence >= 0 and confidence <= 1)),
    constraint chk_analytics_event_time_range check (event_end_time is null or event_time <= event_end_time)
);
